# Generated by Django 3.2.15 on 2022-10-10 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Media', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postsmodel',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='postsmodel',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Media.profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='user.newuser'),
            preserve_default=False,
        ),
    ]
