# Generated by Django 3.2.15 on 2022-10-10 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Media', '0002_auto_20221010_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default='Anonymous User', max_length=50, null=True),
        ),
    ]
